"""
Django settings for MedicalWasteManagementSystem project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment configuration logic:
# - If .env.production exists - Production mode (DEBUG=False)
# - If only .env exists - Development mode (DEBUG=True)
ENV_PRODUCTION_FILE = BASE_DIR / '.env.production'
IS_PRODUCTION = ENV_PRODUCTION_FILE.exists()

if IS_PRODUCTION:
    # Production mode: Load from .env.production
    from decouple import Config, RepositoryEnv
    config = Config(RepositoryEnv(str(ENV_PRODUCTION_FILE)))
    print(f"[Config] Production mode: Loading from {ENV_PRODUCTION_FILE}")
else:
    # Development mode: Use default .env file (already imported at top)
    print(f"[Config] Development mode: Loading from {BASE_DIR / '.env'}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production: DJANGO_SECRET_KEY must be set as environment variable
# In development: Read from .env file
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if IS_PRODUCTION:
        # Production: Absolutely require environment variable
        raise ValueError(
            "CRITICAL SECURITY ERROR: DJANGO_SECRET_KEY environment variable is not set!\n"
            "Production mode requires SECRET_KEY to be set via environment variable.\n"
            "Please check /etc/environment or run initialize.sh to configure properly."
        )
    else:
        # Development: Try .env file, warn if using insecure default
        SECRET_KEY = config('SECRET_KEY', default=None)
        if not SECRET_KEY:
            print("[WARNING] No SECRET_KEY found in .env file!")
            print("[WARNING] Using insecure default key for development ONLY")
            print("[WARNING] This is NOT safe for production!")
            SECRET_KEY = 'django-insecure-development-only-' + os.urandom(24).hex()

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically set based on environment file presence:
# - .env.production exists → DEBUG=False (production)
# - Only .env exists → DEBUG=True (development)
if IS_PRODUCTION:
    DEBUG = False
    print("[Config] DEBUG=False (Production mode)")
else:
    DEBUG = config('DEBUG', default=True, cast=bool)
    print(f"[Config] DEBUG={DEBUG} (Development mode)")

ALLOWED_HOSTS = ['*']  # In production, set specific allowed hosts via environment variable
# config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',  # 允許所有 ngrok 免費網域
    'https://*.ngrok.io',        # 舊版 ngrok 網域 (備用)
]
# Security settings for production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app', 
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Main',
    'MedicalWasteManagementSystem.apps.MedicalWasteManagementSystemConfig',
    'WasteTransportation',
    'WasteManagement',
    'WastePrediction',
    'access_control',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'MedicalWasteManagementSystem.shared_middleware.DatabaseOptimizationMiddleware',
    'MedicalWasteManagementSystem.exception_middleware.UnifiedExceptionHandlingMiddleware',
    'MedicalWasteManagementSystem.audit_middleware.AuditMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'MedicalWasteManagementSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MedicalWasteManagementSystem.permissions.user_group_define',
            ],
        },
    },
]

WSGI_APPLICATION = 'MedicalWasteManagementSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # Units in seconds, default is 5
            'init_command': 'PRAGMA journal_mode=WAL;'  # Enable Write-Ahead Logging
        }
    }
}

# Database Connection Pooling Settings
DATABASE_OPTIONS = {
    'timeout': 30,  # Timeout in seconds for database connections
}

# Ensure logs directory exists
(BASE_DIR / 'logs').mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'audit': {
            '()': 'MedicalWasteManagementSystem.log_formatter.UnifiedLogFormatter',
            'log_type': 'AUDIT',
        },
        'debug': {
            '()': 'MedicalWasteManagementSystem.log_formatter.UnifiedLogFormatter',
            'log_type': 'DEBUG',
        },
        'error': {
            '()': 'MedicalWasteManagementSystem.log_formatter.UnifiedLogFormatter',
            'log_type': 'ERROR',
        },
        'general': {
            '()': 'MedicalWasteManagementSystem.log_formatter.UnifiedLogFormatter',
            'log_type': 'LEVEL',  # Use actual log level (INFO/WARNING/ERROR/etc.)
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Debug log - only in development (DEBUG=True)
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'debug',
            'filters': ['require_debug_true'],
        },
        # Error log - only ERROR and CRITICAL
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'formatter': 'error',
        },
        # Console - INFO and above in production, DEBUG in development
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'general',
        },
        # Audit log - user operations
        'audit_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'latest.log',
            'formatter': 'audit',
            'encoding': 'utf-8',
        },
        'audit_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'audit',
        },
    },
    'loggers': {
        # Django core loggers - only errors
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['debug_file'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'propagate': False,
        },
        # Application loggers
        'MedicalWasteManagementSystem': {
            'handlers': ['console', 'error_file', 'debug_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # Audit logger - user operations
        'audit': {
            'handlers': ['audit_file', 'audit_console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger - catch-all for other modules
        '': {
            'handlers': ['console', 'error_file'],
            'level': 'WARNING',
        },
    },
}

# Upload Request limit
DATA_UPLOAD_MAX_NUMBER_FIELDS = 999999

# SQLite optimization settings
if 'default' in DATABASES and 'sqlite3' in DATABASES['default']['ENGINE']:
    DATABASES['default']['ATOMIC_REQUESTS'] = False
    DATABASES['default']['OPTIONS'] = {
        'timeout': 30,
        'isolation_level': None,  # Use autocommit mode
        'cached_statements': 1000
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# Simplified password validation for development
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 3,  # Much more relaxed minimum length
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Log in as guest: Session Expire
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 604800 # 7 days

# Content Security Policy (CSP) Settings
# Protects against XSS attacks by restricting resource sources
# Note: 'unsafe-inline' is kept for compatibility with ApexCharts and TocasUI
# For full XSS protection, consider migrating to nonce-based CSP in the future

CSP_DEFAULT_SRC = ("'self'",)

# Script sources: Allow self and inline scripts (required for current architecture)
# 'unsafe-inline' allows XSS if user input is not properly escaped
CSP_SCRIPT_SRC = [
    "'self'", 
    "'unsafe-inline'",
    "https://cdnjs.cloudflare.com",
    "https://cdn.jsdelivr.net",
    # 如果有用到 Google Fonts 的 JS 或其他 JS CDN 也要加
]

# Style sources: Allow self and inline styles (required for TocasUI)
CSP_STYLE_SRC = [
    "'self'", 
    "'unsafe-inline'",
    "https://cdnjs.cloudflare.com",
    "https://fonts.googleapis.com",
    "https://cdn.jsdelivr.net",
    "https://cdn.jsdelivr.net", # 重複沒關係，主要是網域要對
    
]

# Image sources: Allow self, data URIs (for charts), and blob (for generated images)
CSP_IMG_SRC = ("'self'", "data:", "blob:")

# Font sources: Only allow from same origin
CSP_FONT_SRC = [
    "'self'",
    "https://fonts.gstatic.com",      # Google Fonts 的字型檔來源
    "https://cdnjs.cloudflare.com",   # 如果你有用 CDN 的 FontAwesome
    "https://cdn.jsdelivr.net",       # 其他常見 CDN
    "data:",
    
    
]

# Connect sources: Only allow AJAX/fetch to same origin
CSP_CONNECT_SRC = ("'self'",)

# Frame ancestors: Prevent all framing (clickjacking protection)
CSP_FRAME_ANCESTORS = ("'none'",)

# Base URI: Restrict to same origin only
CSP_BASE_URI = ("'self'",)

# Form action: Only allow form submissions to same origin
CSP_FORM_ACTION = ("'self'",)

# Object/Embed: Block all plugins (Flash, Java, etc.)
CSP_OBJECT_SRC = ("'none'",)

# Upgrade insecure requests: Automatically upgrade HTTP to HTTPS (when SSL is enabled)
if IS_PRODUCTION and config('SECURE_SSL_REDIRECT', default=False, cast=bool):
    CSP_UPGRADE_INSECURE_REQUESTS = True

# CSRF Cookie Settings
# Keep CSRF_COOKIE_HTTPONLY as False so JavaScript can read it
CSRF_COOKIE_HTTPONLY = False  # Required for JavaScript to read csrftoken cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # Prevent CSRF via cross-site requests