# Generated by Django 5.1.6 on 2025-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalOperationalData',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('bed_occupancy_rate', models.FloatField(blank=True, null=True)),
                ('surgical_cases', models.IntegerField(blank=True, null=True)),
                ('doctor_count', models.IntegerField(blank=True, null=True)),
                ('nurse_count', models.IntegerField(blank=True, null=True)),
                ('total_staff_count', models.IntegerField(blank=True, null=True)),
                ('outpatient_visits', models.IntegerField(blank=True, null=True)),
                ('emergency_visits', models.IntegerField(blank=True, null=True)),
                ('inpatient_visits', models.IntegerField(blank=True, null=True)),
                ('medical_waste_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital_operational_data',
            },
        ),
    ]
