# Generated by Django 5.1.6 on 2025-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WastePrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaloperationaldata',
            options={'verbose_name': '醫院廢棄物因子', 'verbose_name_plural': '醫院廢棄物因子'},
        ),
    ]
