# Generated by Django 5.2.8 on 2026-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_userprofile_code_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真實姓名'),
        ),
    ]
