# Generated by Django 6.0.1 on 2026-01-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clearAgency',
            fields=[
                ('clearAgency_id', models.AutoField(primary_key=True, serialize=False)),
                ('clearAgency_code', models.CharField(max_length=100)),
                ('clearAgency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='processAgency',
            fields=[
                ('processAgency_id', models.AutoField(primary_key=True, serialize=False)),
                ('processAgency_code', models.CharField(max_length=100)),
                ('processAgency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=20, unique=True)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('settlement_time', models.DateTimeField(auto_now_add=True)),
                ('clearAgency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clearagency')),
                ('processAgency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processagency')),
                ('settlement_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='wasteRecord',
            fields=[
                ('wasterecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weighing_personnel', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='過磅時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('TransportRecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportrecord')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('locationPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locationpoint')),
                ('update_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('WasteType_id', models.AutoField(primary_key=True, serialize=False)),
                ('WasteType_name', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('wasteRecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wasterecord')),
            ],
        ),
    ]
