# Generated by Django 5.1.6 on 2025-07-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('enterprise_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='事業機構代碼')),
                ('enterprise_name', models.CharField(max_length=200, verbose_name='事業機構名稱')),
            ],
            options={
                'verbose_name': '事業機構',
                'verbose_name_plural': '事業機構',
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='製程代碼')),
                ('process_name', models.CharField(max_length=200, verbose_name='製程名稱')),
            ],
            options={
                'verbose_name': '製程',
                'verbose_name_plural': '製程',
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('recycler_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='再利用者代碼')),
                ('recycler_name', models.CharField(max_length=200, verbose_name='再利用者名稱')),
                ('recycling_purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='再利用用途')),
                ('recycling_purpose_description', models.TextField(blank=True, null=True, verbose_name='再利用用途說明')),
                ('recycling_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='再利用方式')),
                ('recycler_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='再利用者性質')),
                ('recycling_completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='再利用完成日期/時間')),
                ('actual_recycler_vehicle_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='再利用者實際運載車號')),
            ],
            options={
                'verbose_name': '再利用者',
                'verbose_name_plural': '再利用者',
                'db_table': 'recycler',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='清除者代碼')),
                ('transporter_name', models.CharField(max_length=200, verbose_name='清除者名稱')),
                ('other_transporters', models.TextField(blank=True, null=True, verbose_name='其他清除者')),
            ],
            options={
                'verbose_name': '清除者',
                'verbose_name_plural': '清除者',
                'db_table': 'transporter',
            },
        ),
        migrations.CreateModel(
            name='TreatmentFacility',
            fields=[
                ('treatment_facility_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='處理者代碼')),
                ('treatment_facility_name', models.CharField(max_length=200, verbose_name='處理者名稱')),
            ],
            options={
                'verbose_name': '處理者',
                'verbose_name_plural': '處理者',
                'db_table': 'treatment_facility',
            },
        ),
        migrations.CreateModel(
            name='WasteSubstance',
            fields=[
                ('waste_substance_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='廢棄物/物質代碼')),
                ('waste_substance_name', models.CharField(max_length=500, verbose_name='廢棄物/物質名稱')),
            ],
            options={
                'verbose_name': '廢棄物/物質',
                'verbose_name_plural': '廢棄物/物質',
                'db_table': 'waste_substance',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('declaration_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='申報單代碼')),
                ('declaration_datetime', models.DateTimeField(verbose_name='申報日期/時間')),
                ('declared_weight', models.FloatField(verbose_name='申報重量')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.enterprise', verbose_name='事業機構代碼')),
            ],
            options={
                'verbose_name': '申報單',
                'verbose_name_plural': '申報單',
                'db_table': 'declaration',
            },
        ),
        migrations.CreateModel(
            name='RecoveryVehicle',
            fields=[
                ('recovery_vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='回收運載車號')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.recycler', verbose_name='再利用者代碼')),
            ],
            options={
                'verbose_name': '回收車輛',
                'verbose_name_plural': '回收車輛',
                'db_table': 'recovery_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('recovery_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='回收單代碼')),
                ('recovery_datetime', models.DateTimeField(verbose_name='回收日期/時間')),
                ('recovery_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.recoveryvehicle', verbose_name='回收運載車號')),
                ('recycler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.recycler', verbose_name='再利用者代碼')),
            ],
            options={
                'verbose_name': '回收單',
                'verbose_name_plural': '回收單',
                'db_table': 'recovery',
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('transport_vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='清除運載車號')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.transporter', verbose_name='清除者代碼')),
            ],
            options={
                'verbose_name': '清運車輛',
                'verbose_name_plural': '清運車輛',
                'db_table': 'transport_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('transportation_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='清運單代碼')),
                ('transportation_datetime', models.DateTimeField(verbose_name='清運日期/時間')),
                ('delivery_datetime', models.DateTimeField(verbose_name='運送日期/時間')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.transporter', verbose_name='清除者代碼')),
                ('transport_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.transportvehicle', verbose_name='清除運載車號')),
            ],
            options={
                'verbose_name': '清運單',
                'verbose_name_plural': '清運單',
                'db_table': 'transportation',
            },
        ),
        migrations.CreateModel(
            name='TreatmentVehicle',
            fields=[
                ('treatment_vehicle_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='處理運載車號')),
                ('treatment_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.treatmentfacility', verbose_name='處理者代碼')),
            ],
            options={
                'verbose_name': '處理車輛',
                'verbose_name_plural': '處理車輛',
                'db_table': 'treatment_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='處理單代碼')),
                ('receipt_datetime', models.DateTimeField(verbose_name='收受日期/時間')),
                ('intermediate_treatment_method', models.CharField(max_length=100, verbose_name='中間處理方式')),
                ('final_disposal_method', models.CharField(max_length=100, verbose_name='最終處置方式')),
                ('treatment_completion_datetime', models.DateTimeField(blank=True, null=True, verbose_name='處理完成日期/時間')),
                ('treatment_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.treatmentfacility', verbose_name='處理者代碼')),
                ('treatment_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.treatmentvehicle', verbose_name='處理運載車號')),
            ],
            options={
                'verbose_name': '處理單',
                'verbose_name_plural': '處理單',
                'db_table': 'treatment',
            },
        ),
        migrations.CreateModel(
            name='WasteSubstanceId',
            fields=[
                ('waste_substance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='廢棄物/物質ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.process', verbose_name='製程代碼')),
                ('waste_substance_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.wastesubstance', verbose_name='廢棄物/物質代碼')),
            ],
            options={
                'verbose_name': '廢棄物/物質ID',
                'verbose_name_plural': '廢棄物/物質ID',
                'db_table': 'waste_substance_id',
                'unique_together': {('process', 'waste_substance_code')},
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=50, verbose_name='聯單編號')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='運載車號')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可見')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.declaration', verbose_name='申報單代碼')),
                ('recovery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.recovery', verbose_name='回收單代碼')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.transportation', verbose_name='清運單代碼')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.treatment', verbose_name='處理單代碼')),
                ('waste_substance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteTransportation.wastesubstanceid', verbose_name='廢棄物/物質ID')),
            ],
            options={
                'verbose_name': '聯單',
                'verbose_name_plural': '聯單',
                'db_table': 'manifest',
                'unique_together': {('manifest_number', 'waste_substance_id')},
            },
        ),
    ]
