# Generated by Django 5.1.6 on 2025-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteTransportation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['is_visible', 'manifest_number'], name='manifest_vis_num_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['is_visible', '-id'], name='manifest_vis_id_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['declaration'], name='manifest_decl_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['transportation'], name='manifest_trans_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['treatment'], name='manifest_treat_idx'),
        ),
        migrations.AddIndex(
            model_name='manifest',
            index=models.Index(fields=['recovery'], name='manifest_recov_idx'),
        ),
    ]
