# Generated by Django 5.1.6 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiomedicalWasteProduction',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('red_bag', models.FloatField(blank=True, null=True)),
                ('yellow_bag', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biomedical_waste_production',
            },
        ),
        migrations.CreateModel(
            name='DialysisBucketSoftBagProductionAndDisposalCosts',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('produced_dialysis_bucket', models.FloatField(blank=True, null=True)),
                ('produced_soft_bag', models.FloatField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dialysis_bucket_soft_bag_production_and_disposal_costs',
            },
        ),
        migrations.CreateModel(
            name='GeneralWasteProduction',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('tainan', models.FloatField(blank=True, null=True)),
                ('renwu', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'general_waste_production',
            },
        ),
        migrations.CreateModel(
            name='PaperIronAluminumCanPlasticAndGlassProductionAndRecyclingRevenue',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('paper_produced', models.FloatField(blank=True, null=True)),
                ('iron_aluminum_can_produced', models.FloatField(blank=True, null=True)),
                ('plastic_produced', models.FloatField(blank=True, null=True)),
                ('glass_produced', models.FloatField(blank=True, null=True)),
                ('recycling_revenue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper_iron_aluminum_can_plastic_and_glass_production_and_recycling_revenue',
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalGlassProductionAndDisposalCosts',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('produced', models.FloatField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmaceutical_glass_production_and_disposal_costs',
            },
        ),
    ]
