# Generated by Django 5.1.6 on 2025-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomedicalwasteproduction',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dialysisbucketsoftbagproductionanddisposalcosts',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalwasteproduction',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperironaluminumcanplasticandglassproductionandrecyclingrevenue',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalglassproductionanddisposalcosts',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
