# Generated by Django 5.1.6 on 2025-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0003_alter_biomedicalwasteproduction_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biomedicalwasteproduction',
            options={'verbose_name': '生物醫療廢棄物產出表', 'verbose_name_plural': '生物醫療廢棄物產出表'},
        ),
        migrations.AlterModelOptions(
            name='dialysisbucketsoftbagproductionanddisposalcosts',
            options={'verbose_name': '洗腎桶軟袋產出及處理費用表', 'verbose_name_plural': '洗腎桶軟袋產出及處理費用表'},
        ),
        migrations.AlterModelOptions(
            name='generalwasteproduction',
            options={'verbose_name': '一般事業廢棄物產出表', 'verbose_name_plural': '一般事業廢棄物產出表'},
        ),
        migrations.AlterModelOptions(
            name='paperironaluminumcanplasticandglassproductionandrecyclingrevenue',
            options={'verbose_name': '紙鐵鋁罐塑膠玻璃產出及回收收入表', 'verbose_name_plural': '紙鐵鋁罐塑膠玻璃產出及回收收入表'},
        ),
        migrations.AlterModelOptions(
            name='pharmaceuticalglassproductionanddisposalcosts',
            options={'verbose_name': '藥用玻璃產出及處理費用表', 'verbose_name_plural': '藥用玻璃產出及處理費用表'},
        ),
    ]
