# Generated by Django 5.1.6 on 2025-08-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0004_alter_biomedicalwasteproduction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
                'db_table': 'departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '廢棄物種類',
                'verbose_name_plural': '廢棄物種類',
                'db_table': 'waste_types',
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=7)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.department')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.wastetype')),
            ],
            options={
                'verbose_name': '廢棄物紀錄',
                'verbose_name_plural': '廢棄物紀錄',
                'db_table': 'waste_records',
                'indexes': [models.Index(fields=['date'], name='waste_recor_date_9ae752_idx'), models.Index(fields=['department', 'date'], name='waste_recor_departm_6344a3_idx'), models.Index(fields=['waste_type', 'date'], name='waste_recor_waste_t_dd827a_idx')],
                'unique_together': {('date', 'department', 'waste_type')},
            },
        ),
    ]
