# Generated by Django 5.1.6 on 2025-09-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0006_alter_department_wastetype_wasterecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWasteTypeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '部門廢棄物種類映射',
                'verbose_name_plural': '部門廢棄物種類映射',
                'db_table': 'department_waste_type_mappings',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waste_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_waste_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='unit',
            field=models.CharField(choices=[('metric_ton', '公噸'), ('kilogram', '公斤')], default='metric_ton', max_length=50),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['created_by'], name='waste_recor_created_f7a49b_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['updated_by'], name='waste_recor_updated_42ed57_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetype',
            index=models.Index(fields=['name'], name='waste_types_name_c64c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='wastetype',
            index=models.Index(fields=['is_active'], name='waste_types_is_acti_44b85a_idx'),
        ),
        migrations.AddField(
            model_name='departmentwastetypemapping',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.department'),
        ),
        migrations.AddField(
            model_name='departmentwastetypemapping',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.wastetype'),
        ),
        migrations.AddIndex(
            model_name='departmentwastetypemapping',
            index=models.Index(fields=['department', 'waste_type'], name='department__departm_d95f89_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentwastetypemapping',
            index=models.Index(fields=['is_active'], name='department__is_acti_ce1bef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentwastetypemapping',
            unique_together={('department', 'waste_type')},
        ),
    ]
