# Generated by Django 5.1.6 on 2025-09-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0007_departmentwastetypemapping_department_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentWasteTypeMapping',
        ),
    ]
