# Generated by Django 5.1.6 on 2025-10-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0009_init_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalwasteproduction',
            name='field_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomedicalwasteproduction',
            name='total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='generalwasteproduction',
            name='total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
