# Generated by Django 6.0.1 on 2026-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0010_generalwasteproduction_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='unit',
            field=models.CharField(choices=[('metric_ton', '公噸'), ('kilogram', '公斤'), ('gram', '公克')], default='metric_ton', max_length=50),
        ),
    ]
