# Generated by Django 6.0.1 on 2026-03-11 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0011_department_code_alter_wastetype_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_records', to='WasteManagement.department'),
        ),
    ]
