# Generated by Django 6.0.1 on 2026-03-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0012_alter_wasterecord_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_types', to='WasteManagement.wastetype'),
        ),
    ]
