# Generated by Django 6.0.1 on 2026-03-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0013_alter_wasterecord_waste_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_order', 'name', 'code'], 'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_9f933a_idx'),
        ),
    ]
