# Generated by Django 6.0.1 on 2026-03-28 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0014_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clearAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '清理機構',
                'db_table': 'clear_agency',
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '定點',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='processAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '處理機構',
                'db_table': 'process_agency',
            },
        ),
        migrations.CreateModel(
            name='TransportRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('settle_time', models.DateTimeField(auto_now_add=True)),
                ('clear_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.clearagency')),
                ('process_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.processagency')),
                ('settler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to=settings.AUTH_USER_MODEL, verbose_name='結算人員')),
            ],
            options={
                'verbose_name': '載運紀錄',
                'db_table': 'transport_record',
            },
        ),
        migrations.CreateModel(
            name='WasteRecord_New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_transported', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='過磅時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='過磅人員')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_records', to='WasteManagement.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.locationpoint')),
                ('transportrecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WasteManagement.transportrecord')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL, verbose_name='更新人員')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_types', to='WasteManagement.wastetype')),
            ],
            options={
                'verbose_name': '廢棄物紀錄',
                'db_table': 'waste_record',
            },
        ),
    ]
