# Generated by Django 5.2.8 on 2026-07-15 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0015_clearagency_locationpoint_processagency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearagency',
            options={'verbose_name': '清理機構', 'verbose_name_plural': '清理機構'},
        ),
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'verbose_name': '定點', 'verbose_name_plural': '定點'},
        ),
        migrations.AlterModelOptions(
            name='processagency',
            options={'verbose_name': '處理機構', 'verbose_name_plural': '處理機構'},
        ),
        migrations.AlterModelOptions(
            name='transportrecord',
            options={'verbose_name': '載運紀錄', 'verbose_name_plural': '載運紀錄'},
        ),
        migrations.AlterModelOptions(
            name='wasterecord_new',
            options={'verbose_name': '新廢棄物紀錄', 'verbose_name_plural': '新廢棄物紀錄'},
        ),
        migrations.RemoveField(
            model_name='wasterecord_new',
            name='is_transported',
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='settle_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='結算時間'),
        ),
        migrations.AlterField(
            model_name='wasterecord_new',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='過磅時間'),
        ),
        migrations.AlterField(
            model_name='wasterecord_new',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='wasterecord_new',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_types', to='WasteManagement.wastetype'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='unit',
            field=models.CharField(choices=[('metric_ton', '公噸'), ('kilogram', '公斤')], default='metric_ton', max_length=50),
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_min', models.FloatField(blank=True, default=1, help_text='重量最小限制 (kg)', null=True)),
                ('weight_max', models.FloatField(blank=True, default=100, help_text='重量最大限制 (kg)', null=True)),
                ('time_frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每週'), ('monthly', '每月')], default='daily', max_length=20)),
                ('overdue_hours', models.IntegerField(blank=True, default=24, help_text='逾期小時數', null=True)),
                ('weighting_counts', models.IntegerField(blank=True, default=3, help_text='每日過磅次數標準', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configs', to='WasteManagement.department')),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configs', to='WasteManagement.wastetype')),
            ],
        ),
    ]
